In [1]:
#3 find the shape size and dimensions of the following array


In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [3]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
arr.shape

(3, 4)

In [5]:
arr.size

12

In [6]:
arr.ndim # since we have 2 square braces on the above array

2

In [7]:
#problem no.4>> write python code to access the first row of the following array?

In [8]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
arr[0:1]

array([[1, 2, 3, 4]])

In [10]:
#problem no.5>> how do you access the element at the third row and fourth column from the given numpy array?

In [11]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
# element at third row and fourth column
arr[2,3]

12

In [13]:
#problem no.6>> write code to extract all odd indexed elements from the given numpy array?

In [14]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr[1:2,[1,3]] # hence you find the elements at 1th row amd both 1th and 3rd column

array([[6, 8]])

In [16]:
#7 how can you generate a random 3*3 matrix with values between 0 and 1

In [17]:
np.random.rand(2,3)

array([[0.50094474, 0.84909212, 0.4640467 ],
       [0.40952711, 0.84843351, 0.00500335]])

In [18]:
#9 write a code to increase the dimension of the following array?

In [19]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
(arr.ndim)+1

3

In [21]:
#10 how to transpose the following array in numpy?

In [22]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [24]:
# problem no-11>>
matrixA = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
matrixB = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
matrixA

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
matrixB

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [27]:
matrixA*8   # index wise multiplication by 7,8
matrixB*7

matrix([[ 7, 14, 21],
        [28, 35, 42],
        [49, 56, 63]])

In [28]:
matrixA@matrixB # matrix multiplication

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [29]:
matrixA+matrixB     # matrix additon

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [30]:
matrixB-matrixA        # matrix subtraction

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [31]:
matrixB/matrixA # matrix division 

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [32]:
# problem no 14>> what does the np.reshape function do, how is it used?

In [33]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
arr.reshape(4,3) # it is used for reshaping the style of the matrix like we did sideby coverting to order (4,3) from order(3,4)
                 # but it reshape the order with the fixed elements 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [35]:
# problem no 15>> what is broadcasting in numpy?
#Ans:- This process involves certain rules that allow the smaller array to be ‘broadcast’ across the larger one, ensuring that they have compatible shapes for these operations.

In [36]:
arr = np.zeros((3,4))

In [37]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
p = np.array([1,2,3,4,])

In [39]:
p

array([1, 2, 3, 4])

In [40]:
arr+p

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [41]:
arr*1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
arr+4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [43]:
#problem no 13>> what is the significance of the np.linalg.inv function?

In [44]:
arr1 = np.matrix([[2,3],[4,5]])

In [45]:
arr1

matrix([[2, 3],
        [4, 5]])

In [46]:
np.linalg.inv(arr1)

matrix([[-2.5,  1.5],
        [ 2. , -1. ]])

In [47]:
arr2 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [48]:
arr2

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [49]:
np.linalg.inv(arr1)

matrix([[-2.5,  1.5],
        [ 2. , -1. ]])

In [ ]:
#problem no 12>>what function in numpy can be used to swap the byte order of an array?

In [50]:
arr = np.array([0,1,2,3,4,0,6])

In [51]:
arr

array([0, 1, 2, 3, 4, 0, 6])

In [52]:
arr.byteswap()

array([                 0,  72057594037927936, 144115188075855872,
       216172782113783808, 288230376151711744,                  0,
       432345564227567616])

In [ ]:
#problem no 8>> difference between np.random.rand and np.random.randn?

In [53]:
'''The numpy.random.randn() function creates an array of specified shape and fills it 
with random values as per standard normal distribution.''' 

'The numpy.random.randn() function creates an array of specified shape and fills it \nwith random values as per standard normal distribution.'

In [ ]:
#problem no1>> what is the python library?why do we use python library?

In [58]:
'''A collection of modules that are linked together is also known as a Python library'''

'A collection of modules that are linked together is also known as a Python library'

In [59]:
''' It has code bundles that can be used again and again in different programs. For programmers, it makes Python programming easier and simpler. Since then, we will not need to compose the same code for various projects.'''

' It has code bundles that can be used again and again in different programs. For programmers, it makes Python programming easier and simpler. Since then, we will not need to compose the same code for various projects.'

In [ ]:
#problem no 2>> what is the difference between numpy array and list?

In [60]:
'''1.numpy array is much faster than the list in implementation because numpy array elements have same datatypes rather than list'''

'1.numpy array is much faster than the list in implementation because numpy array elements have same datatypes rather than list'

In [ ]:
'''2.numpy array have contiguous memory location but on the list have non-cont